(()=>{
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=cents=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(cents||0)/100);
  let active=false,products=[];
  function productData(p){return {name:p.name||'Produto',price:Number(p.base_price_cents||0)>0?money(p.base_price_cents):'consulte o valor',description:String(p.description||'').trim().replace(/\s+/g,' ').slice(0,180),category:p.category_name||'',sku:p.sku||''}}
  const starts=['Conheça','Destaque para','Veja agora','Uma escolha para você:','Procurando qualidade? Conheça','Novo destaque:','Confira','Descubra'];
  const benefits=['qualidade e praticidade','detalhes pensados para o seu ambiente','uma opção versátil para seu projeto','acabamento e funcionalidade','uma solução para renovar seu espaço','opções para diferentes necessidades'];
  const ctas=['Confira na loja.','Veja todos os detalhes.','Acesse e saiba mais.','Solicite seu orçamento.','Veja fotos e informações.','Conheça as opções disponíveis.'];
  function generate(p,count){const x=productData(p),rows=[];for(let i=0;i<count;i++){const start=starts[i%starts.length],benefit=benefits[Math.floor(i/starts.length)%benefits.length],cta=ctas[(i*3)%ctas.length],title=`${start} ${x.name}`.slice(0,100),desc=x.description||`Produto com ${benefit}.`,text=`${title}. ${desc} ${x.price!== 'consulte o valor'?`A partir de ${x.price}. `:''}${cta}`.replace(/\s+/g,' ').trim();rows.push({variation:i+1,title,text,headline:x.name,description:desc,cta:'SAIBA_MAIS',productId:p.id,sku:x.sku})}return rows}
  function csv(rows){const cols=['variation','title','text','headline','description','cta','productId','sku'];const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return [cols.join(','),...rows.map(r=>cols.map(k=>q(r[k])).join(','))].join('\n')}
  function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function load(){const d=await api('catalog/products');products=d.products||[]}
  async function render(){active=true;$$('#admin-nav button').forEach(b=>b.classList.toggle('active',b.id==='admin-ads-nav'));$('#view-title').textContent='Anúncios';$('#view-subtitle').textContent='Crie variações sem consumir IA';const c=$('#view-content');c.innerHTML='<div class="empty">Carregando produtos…</div>';await load();c.innerHTML=`<section class="panel"><div class="panel-head"><div><h2>Gerador de anúncios</h2><p>Cria variações de texto por combinação de modelos. Não faz chamada de IA e não publica automaticamente.</p></div></div><div class="form-grid"><div class="form-field"><label>Produto</label><select id="ads-product"><option value="">Selecione…</option>${products.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></div><div class="form-field"><label>Quantidade de variações</label><input id="ads-count" type="number" min="1" max="50" value="10"></div></div><div class="form-actions"><button id="ads-generate" class="primary-btn">Gerar variações</button><button id="ads-export-csv" class="ghost-btn" disabled>Exportar CSV</button><button id="ads-export-json" class="ghost-btn" disabled>Exportar JSON</button></div><small class="field-hint">A publicação no Meta/Google continuará separada e só será habilitada quando a conta e as credenciais seguras estiverem configuradas.</small></section><section id="ads-results" class="panel" style="margin-top:16px"><div class="empty">Escolha um produto e gere as variações.</div></section>`;let rows=[];$('#ads-generate').onclick=()=>{const p=products.find(x=>x.id===$('#ads-product').value);if(!p)return alert('Selecione um produto.');const n=Math.max(1,Math.min(50,Number($('#ads-count').value||10)));rows=generate(p,n);$('#ads-results').innerHTML=`<div class="panel-head"><h2>${rows.length} variações</h2><span>0 uso de IA</span></div><div class="product-ad-list">${rows.map(r=>`<article class="product-ad-card"><small>Variação ${r.variation}</small><strong>${esc(r.title)}</strong><p>${esc(r.text)}</p><button type="button" class="ghost-btn" data-ad-copy="${r.variation-1}">Copiar</button></article>`).join('')}</div>`;$$('[data-ad-copy]').forEach(b=>b.onclick=async()=>{const r=rows[Number(b.dataset.adCopy)],text=`${r.title}\n\n${r.text}`;try{await navigator.clipboard.writeText(text);toast('Anúncio copiado')}catch{prompt('Copie:',text)}});$('#ads-export-csv').disabled=false;$('#ads-export-json').disabled=false};$('#ads-export-csv').onclick=()=>rows.length&&download('anuncios-radz.csv','\ufeff'+csv(rows),'text/csv;charset=utf-8');$('#ads-export-json').onclick=()=>rows.length&&download('anuncios-radz.json',JSON.stringify(rows,null,2),'application/json')}
  function install(){const nav=$('#admin-nav');if(!nav||$('#admin-ads-nav'))return;const productsBtn=$('[data-view="products"]',nav),b=document.createElement('button');b.id='admin-ads-nav';b.type='button';b.innerHTML='<span>◉</span>Anúncios';b.onclick=e=>{e.preventDefault();render().catch(err=>{$('#view-content').innerHTML=`<div class="panel empty">${esc(err.message)}</div>`})};productsBtn?.after(b)}
  document.addEventListener('click',e=>{if(e.target.closest('#admin-nav [data-view]'))active=false},true);
  const obs=new MutationObserver(install);obs.observe(document.documentElement,{childList:true,subtree:true});install();
})();
