// ============================================================
// CARRINHO - RADZ HUB / STOREFRONT
// ESTRUTURA GENÉRICA
// ============================================================

const CHAVE_PEDIDO = "salvatex_pedido_atual";

function criarDetalhe(detalhe){const div=document.createElement("div"),strong=document.createElement("strong"),span=document.createElement("span");strong.textContent=(detalhe.rotulo||"Detalhe")+": ";span.textContent=detalhe.valor??"—";div.append(strong,span);return div}
function criarItemCarrinho(item){const artigo=document.createElement("article");artigo.className="carrinho-item";if(item.imagem){const imagem=document.createElement("img");imagem.className="carrinho-item-imagem";imagem.src=item.imagem;imagem.alt=item.nome;imagem.onerror=()=>{const p=document.createElement("div");p.className="carrinho-item-sem-imagem";p.textContent=item.nome;imagem.replaceWith(p)};artigo.appendChild(imagem)}else{const p=document.createElement("div");p.className="carrinho-item-sem-imagem";p.textContent=SalvatexCarrinho.nomeCategoria(item.categoria);artigo.appendChild(p)}const conteudo=document.createElement("div");conteudo.className="carrinho-item-conteudo";const topo=document.createElement("div");topo.className="carrinho-item-topo";const titulo=document.createElement("h3");titulo.className="carrinho-item-titulo";titulo.textContent=item.nome;const preco=document.createElement("div");preco.className="carrinho-item-preco";preco.textContent=SalvatexCarrinho.brl(item.total);topo.append(titulo,preco);conteudo.appendChild(topo);const categoria=document.createElement("div");categoria.style.cssText="margin-top:4px;font-size:11px;color:#746c63";categoria.textContent=SalvatexCarrinho.nomeCategoria(item.categoria);conteudo.appendChild(categoria);if(Array.isArray(item.detalhes)&&item.detalhes.length){const detalhes=document.createElement("div");detalhes.className="carrinho-item-detalhes";item.detalhes.forEach(d=>detalhes.appendChild(criarDetalhe(d)));conteudo.appendChild(detalhes)}if(Number(item.quantidade)>1){const q=document.createElement("div");q.style.cssText="margin-top:10px;font-size:12px;color:#746c63";q.textContent="Quantidade: "+item.quantidade;conteudo.appendChild(q)}const acoes=document.createElement("div");acoes.className="carrinho-item-acoes";const remover=document.createElement("button");remover.type="button";remover.className="carrinho-remover";remover.textContent="Remover";remover.onclick=()=>{SalvatexCarrinho.removerItem(item.id);renderizarCarrinho()};acoes.appendChild(remover);conteudo.appendChild(acoes);artigo.appendChild(conteudo);return artigo}
function renderizarCategoriasResumo(carrinho){const resumo=document.getElementById("carrinho-resumo");if(!resumo)return;document.getElementById("resumo-cortinas")?.closest(".carrinho-resumo-linha")?.style.setProperty("display","none");document.getElementById("resumo-linha-trilhos")?.style.setProperty("display","none");resumo.querySelectorAll(".resumo-categoria-dinamica").forEach(l=>l.remove());const divisor=resumo.querySelector(".carrinho-resumo-divisor"),totais=SalvatexCarrinho.calcularTotaisPorCategoria(carrinho);Object.entries(totais).forEach(([categoria,valor])=>{const linha=document.createElement("div");linha.className="carrinho-resumo-linha resumo-categoria-dinamica";const nome=document.createElement("span"),preco=document.createElement("strong");nome.textContent=SalvatexCarrinho.nomeCategoria(categoria);preco.textContent=SalvatexCarrinho.brl(valor);linha.append(nome,preco);divisor?resumo.insertBefore(linha,divisor):resumo.appendChild(linha)})}
function atualizarResumoCarrinho(carrinho){renderizarCategoriasResumo(carrinho);const total=SalvatexCarrinho.calcularTotal(carrinho),te=document.getElementById("carrinho-total"),se=document.getElementById("carrinho-subtotal"),p=document.getElementById("carrinho-parcelamento");if(te)te.textContent=SalvatexCarrinho.brl(total);if(se)se.textContent=SalvatexCarrinho.brl(total);if(p){const parcelas=Number(CONFIG?.parcelas||10);p.textContent=total>0?`ou ${parcelas}x de ${SalvatexCarrinho.brl(total/parcelas)} sem juros`:""}}
function mostrarCarrinhoVazio(){localStorage.removeItem(CHAVE_PEDIDO);const layout=document.getElementById("carrinho-layout");if(!layout)return;layout.innerHTML=`<div class="carrinho-vazio"><div class="carrinho-vazio-icone">🛒</div><h2>Seu carrinho está vazio</h2><p>Adicione produtos para continuar com sua compra.</p><a href="index.html#produtos" class="carrinho-vazio-botao">Ver produtos</a></div>`;layout.style.display="block"}
function renderizarCarrinho(){const carrinho=SalvatexCarrinho.obterCarrinho();if(!carrinho.length){mostrarCarrinhoVazio();return}const container=document.getElementById("carrinho-itens");if(!container)return;container.innerHTML="";carrinho.forEach(item=>container.appendChild(criarItemCarrinho(item)));atualizarResumoCarrinho(carrinho)}
function continuarParaEntrega(){const carrinho=SalvatexCarrinho.obterCarrinho();if(!carrinho.length)return;const totais=SalvatexCarrinho.calcularTotaisPorCategoria(carrinho),total=SalvatexCarrinho.calcularTotal(carrinho),pedido=SalvatexPedido.criarPedido(carrinho,{status:"rascunho",etapa:"entrega",totaisPorCategoria:totais,totais:{produtos:total,frete:null,desconto:0,total}});SalvatexPedido.salvarPedido(pedido);window.location.href="checkout.html"}
const botaoFinalizar=document.getElementById("finalizar-pedido");if(botaoFinalizar)botaoFinalizar.addEventListener("click",continuarParaEntrega);renderizarCarrinho();
