// ============================================================
// CONFIGURAÇÃO LOCAL SEGURA / MULTI-TENANT
// ============================================================
const CONFIG={whatsapp:"",parcelas:10,freteGratisMinimo:0,producao:"",entrega:"",altura:{alturaEntradaMaxima:5,calculoMaximo:3.20,inicioAcrescimo:2.80,acrescimoApos280:.25,acimaMaximo:{modo:"consulta",texto:"Medida fora do limite automático. Solicite orçamento personalizado.",textoBotao:"Solicitar orçamento",permitirCarrinho:false}},barra:{faixasSemAcrescimo:[],acimaDe280:20},instalacao:{},cores:{},precos:{},franzimentos:[{valor:2,rotulo:"2x"},{valor:2.5,rotulo:"2,5x"},{valor:3,rotulo:"3x"}],mediaConfigurador:[],estoqueCombinacoes:{},configuradorTecidos:{},configurador:{id:"wave",nome:"Configurador",ativo:false,modelo:"Wave",descricao:""},labels:{kicker:"CONFIGURADOR",pageTitle:"Configure seu produto sob medida",pageDescription:"Informe as medidas e escolha as opções disponíveis.",formTitle:"Configure seu produto",formSubtitle:"Escolha as características abaixo para calcular seu produto.",step1:"Produto",step2:"Material",step3:"Opção",step4:"Acabamento",step5:"Resumo",widthLabel:"Largura",heightLabel:"Altura",modelLabel:"Modelo",fabricLabel:"Material",liningLabel:"Opção",colorLabel:"Cor",trackLabel:"Acabamento",summaryTitle:"Resumo",addToCartLabel:"Adicionar ao carrinho"}};
function mesclarConfig(alvo,fonte){if(!fonte||typeof fonte!=="object")return alvo;Object.entries(fonte).forEach(([chave,valor])=>{if(valor&&typeof valor==="object"&&!Array.isArray(valor)&&alvo[chave]&&typeof alvo[chave]==="object"&&!Array.isArray(alvo[chave]))mesclarConfig(alvo[chave],valor);else alvo[chave]=valor});return alvo}
function aplicarConfigurador(wave){if(!wave||typeof wave!=="object")return;const medidas=wave.medidas||{};CONFIG.configurador={id:wave.id||"wave",nome:wave.nome||"Configurador",ativo:wave.ativo===true,modelo:wave.modelo||wave.nome||"Produto",descricao:wave.descricao||""};if(medidas.alturaEntradaMaxima!=null)CONFIG.altura.alturaEntradaMaxima=Number(medidas.alturaEntradaMaxima);if(medidas.calculoMaximo!=null)CONFIG.altura.calculoMaximo=Number(medidas.calculoMaximo);if(medidas.inicioAcrescimo!=null)CONFIG.altura.inicioAcrescimo=Number(medidas.inicioAcrescimo);if(medidas.acrescimoPercentual!=null)CONFIG.altura.acrescimoApos280=Number(medidas.acrescimoPercentual)/100;CONFIG.altura.acimaMaximo=medidas.acimaMaximo||CONFIG.altura.acimaMaximo;CONFIG.barra.faixasSemAcrescimo=Array.isArray(wave.barra?.faixas)?wave.barra.faixas:[];if(wave.barra?.acimaInicio!=null)CONFIG.barra.acimaDe280=Number(wave.barra.acimaInicio);CONFIG.franzimentos=Array.isArray(wave.franzimentos)?wave.franzimentos:[];CONFIG.instalacao=wave.trilhos&&typeof wave.trilhos==="object"?wave.trilhos:{};CONFIG.cores={};CONFIG.precos={};CONFIG.configuradorTecidos={};if(wave.tecidos&&typeof wave.tecidos==="object"){Object.entries(wave.tecidos).forEach(([nome,t])=>{if(t?.ativo===false)return;CONFIG.configuradorTecidos[nome]=t&&typeof t==='object'?t:{};CONFIG.cores[nome]=Array.isArray(t.cores)?t.cores:[];CONFIG.precos[nome]=t.forros&&typeof t.forros==="object"?t.forros:{}})}CONFIG.mediaConfigurador=Array.isArray(wave.midia)?wave.midia:[];CONFIG.estoqueCombinacoes=wave.estoqueCombinacoes&&typeof wave.estoqueCombinacoes==="object"?{...wave.estoqueCombinacoes}:{};if(wave.labels&&typeof wave.labels==='object')mesclarConfig(CONFIG.labels,wave.labels)}
window.CONFIG=CONFIG;
window.CONFIG_READY=(async()=>{const params=new URLSearchParams(window.location.search);const raw=String(params.get("id")||"wave").trim().toLowerCase();const configuratorId=/^[a-z0-9][a-z0-9-]{1,47}$/.test(raw)?raw:"wave";try{const configUrl="/api/configurators/"+encodeURIComponent(configuratorId);const[siteResp,cfgResp]=await Promise.all([fetch("/api/store-config",{cache:"no-store"}),fetch(configUrl,{cache:"no-store"})]);if(siteResp.ok){const d=await siteResp.json();if(d?.ok&&d.config)mesclarConfig(CONFIG,d.config)}if(cfgResp.ok){const d=await cfgResp.json(),cfg=d?.wave||d?.configurator;if(d?.ok&&cfg){aplicarConfigurador(cfg);CONFIG.configurador.id=cfg.id||configuratorId;CONFIG.configurador.modelo=cfg.modelo||cfg.nome||"Produto";CONFIG.configurador.descricao=cfg.descricao||"";console.info("Configurador carregado da loja:",configuratorId,d.source||"",d.updatedAt||"")}}else console.warn("Configurador não disponível para esta loja:",configuratorId,cfgResp.status)}catch(erro){console.warn("Configuração remota indisponível; mantendo fallback vazio.",erro)}return CONFIG})();
if(!document.querySelector('script[data-radz-configurator-labels]')){const s=document.createElement('script');s.src='/js/configurador-labels.js?v=20260820-1';s.dataset.radzConfiguratorLabels='1';document.head.appendChild(s)}
