(function(){
  async function config(){return fetch('/api/turnstile-config',{cache:'no-store'}).then(r=>r.json()).catch(()=>({enabled:false}))}
  async function init(){const form=document.getElementById('contact-form');if(!form)return;let widget=null;const cfg=await config();if(cfg.enabled){for(let i=0;i<40&&!window.turnstile;i++)await new Promise(r=>setTimeout(r,100));if(window.turnstile)widget=turnstile.render(form.querySelector('.contact-turnstile'),{sitekey:cfg.sitekey,theme:'light'})}
    try{const d=await fetch('/api/layout',{cache:'no-store'}).then(r=>r.json()),number=String(d.layout?.footer?.whatsapp||d.config?.footer?.whatsapp||'').replace(/\D/g,'');const link=document.querySelector('[data-contact-whatsapp]');if(link&&number){link.href='https://wa.me/'+number;link.textContent='WhatsApp: +'+number}}catch{}
    form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]'),feedback=form.querySelector('.contact-feedback'),data=new FormData(form);button.disabled=true;feedback.textContent='Enviando…';feedback.style.color='';try{const response=await fetch('/api/contact',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:data.get('name'),email:data.get('email'),phone:data.get('phone'),message:data.get('message'),website:data.get('website'),turnstileToken:widget!==null&&window.turnstile?turnstile.getResponse(widget):''})}),body=await response.json();if(!response.ok)throw new Error(body.message||'Não foi possível enviar.');feedback.style.color='#08752b';feedback.textContent=body.message;form.reset();if(widget!==null&&window.turnstile)turnstile.reset(widget)}catch(error){feedback.style.color='#a40000';feedback.textContent=error.message;if(widget!==null&&window.turnstile)turnstile.reset(widget)}finally{button.disabled=false}})
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();

