(function(){
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const brl=c=>(Number(c||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const statusNames={aguardando_pagamento:'Aguardando pagamento',pago:'Pagamento aprovado',em_producao:'Em produção',pronto:'Pronto para envio',enviado:'Enviado',entregue:'Entregue',cancelado:'Cancelado',reembolsado:'Reembolsado'};
const statusName=s=>statusNames[s]||String(s||'—').replaceAll('_',' ');
const safeUrl=value=>{try{const u=new URL(String(value||''));return u.protocol==='https:'?u.href:''}catch{return''}};
let cfg=null,widgets=new Map();
async function turnstileConfig(){return cfg||(cfg=await fetch('/api/turnstile-config',{cache:'no-store'}).then(r=>r.json()).catch(()=>({enabled:false})))}
async function renderTurnstile(form){if(!form)return;const c=await turnstileConfig(),slot=form.querySelector('.account-turnstile');if(!c.enabled||!slot||widgets.has(form))return;for(let i=0;i<40&&!window.turnstile;i++)await new Promise(r=>setTimeout(r,100));if(window.turnstile)widgets.set(form,turnstile.render(slot,{sitekey:c.sitekey,theme:'light'}))}
function token(form){const id=widgets.get(form);return id!==undefined&&window.turnstile?turnstile.getResponse(id):''}
function reset(form){const id=widgets.get(form);if(id!==undefined&&window.turnstile)turnstile.reset(id)}
async function request(form,path,data,method='POST'){const out=form.querySelector('.account-feedback'),button=form.querySelector('[type=submit]');out.textContent='';button.disabled=true;try{const r=await fetch(path,{method,headers:{'content-type':'application/json'},body:JSON.stringify({...data,turnstileToken:token(form)})}),raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw new Error('O servidor não conseguiu concluir a operação.')}if(!r.ok)throw new Error(d.message||'Não foi possível continuar.');out.style.color='#08752b';out.textContent=d.message||'Concluído.';return d}catch(e){out.style.color='#a40000';out.textContent=e.message;reset(form);return null}finally{button.disabled=false}}
function setupLogin(){const f=document.getElementById('email-login-form');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const x=new FormData(f),d=await request(f,'/api/auth/login',{email:x.get('email'),password:x.get('password')});if(d)location.reload()};renderTurnstile(f)}
function showSection(name){document.querySelectorAll('.account-section').forEach(s=>s.hidden=s.id!==`account-section-${name}`);document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===name))}
function setupSections(){document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>showSection(b.dataset.section))}
async function loadProfile(){const r=await fetch('/api/account/profile',{cache:'no-store'}),d=await r.json();if(!r.ok)return;const p=d.profile,f=document.getElementById('profile-form'),a=p.address||{};for(const[k,v]of Object.entries({name:p.name,email:p.email,phone:p.phone,cpf:p.cpf,cep:a.cep,street:a.street,number:a.number,complement:a.complement,district:a.district,city:a.city,state:a.state}))if(f.elements[k])f.elements[k].value=v||'';const ef=document.getElementById('email-change-form');if(!d.emailServiceEnabled){ef.querySelector('button').disabled=true;ef.querySelector('.account-feedback').textContent='A confirmação por e-mail será liberada após configurar o serviço de envio.'}f.onsubmit=async e=>{e.preventDefault();const x=new FormData(f);await request(f,'/api/account/profile',{name:x.get('name'),phone:x.get('phone'),address:{cep:x.get('cep'),street:x.get('street'),number:x.get('number'),complement:x.get('complement'),district:x.get('district'),city:x.get('city'),state:x.get('state')}},'PATCH')};ef.onsubmit=async e=>{e.preventDefault();const x=new FormData(ef);await request(ef,'/api/account/email-change',{newEmail:x.get('newEmail'),currentPassword:x.get('currentPassword')})};renderTurnstile(ef);const pf=document.getElementById('password-form');pf.onsubmit=async e=>{e.preventDefault();const x=new FormData(pf);if(x.get('newPassword')!==x.get('confirmPassword'))return pf.querySelector('.account-feedback').textContent='As novas senhas não coincidem.';const d=await request(pf,'/api/account/password',{currentPassword:x.get('currentPassword'),newPassword:x.get('newPassword')});if(d)pf.reset()};renderTurnstile(pf)}
function closeOrder(){document.querySelector('.account-modal')?.remove()}
function row(label,value){return `<div class="account-detail-row"><span>${esc(label)}</span><strong>${esc(value||'—')}</strong></div>`}
async function openOrder(id){const r=await fetch(`/api/account/order/${encodeURIComponent(id)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.message||'Não foi possível abrir o pedido.');const o=d.order,f=o.freight||{},url=safeUrl(f.trackingUrl);const items=(d.items||[]).map(i=>`<div class="account-item"><div><strong>${esc(i.name)}</strong><small>${esc(i.category_name||i.category||'')}</small></div><strong>${brl(i.total_cents)}</strong></div>`).join('');const tracking=o.status==='enviado'||o.status==='entregue'||f.trackingCode?`<section class="account-tracking-card"><h3>Rastreamento</h3>${row('Transportadora',f.carrier)}${row('Código de rastreio',f.trackingCode)}${url?`<a class="account-tracking-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">ACOMPANHAR ENTREGA</a>`:''}</section>`:`<section class="account-tracking-card account-tracking-pending"><h3>Rastreamento</h3><p>O código e o link aparecerão aqui assim que o pedido for enviado.</p></section>`;const docs=(d.invoices||[]).map(x=>`<a class="account-doc" href="/api/account/document?orderId=${encodeURIComponent(o.id)}&key=${encodeURIComponent(x.key)}">${esc(x.name||'Documento')}</a>`).join('');const modal=document.createElement('div');modal.className='account-modal';modal.innerHTML=`<div class="account-modal-card" role="dialog" aria-modal="true" aria-labelledby="account-order-title"><button class="account-modal-close" type="button" aria-label="Fechar">×</button><span class="account-modal-kicker">PEDIDO</span><h2 id="account-order-title">${esc(o.order_number)}</h2><div class="account-order-status account-status-${esc(o.status)}">${esc(statusName(o.status))}</div><div class="account-detail-grid">${row('Data do pedido',new Date(o.created_at).toLocaleDateString('pt-BR'))}${row('Total',brl(o.total_cents))}</div>${tracking}<section class="account-order-items"><h3>Itens do pedido</h3>${items||'<p>Nenhum item encontrado.</p>'}</section>${docs?`<section><h3>Documentos</h3>${docs}</section>`:''}</div>`;modal.querySelector('.account-modal-close').onclick=closeOrder;modal.onclick=e=>{if(e.target===modal)closeOrder()};document.body.appendChild(modal);modal.querySelector('.account-modal-close').focus()}
async function loadOrders(){const box=document.getElementById('account-orders'),r=await fetch('/api/account/orders',{cache:'no-store'}),d=await r.json();if(!r.ok){box.innerHTML=`<div class="account-empty">${esc(d.message||'Não foi possível carregar os pedidos.')}</div>`;return}box.innerHTML=(d.orders||[]).map(o=>`<article class="account-order"><div><span>Pedido</span><strong>${esc(o.order_number)}</strong><small>${new Date(o.created_at).toLocaleDateString('pt-BR')}</small></div><div><span>Status</span><strong class="account-status-text">${esc(statusName(o.status))}</strong></div><div><span>Total</span><strong>${brl(o.total_cents)}</strong></div><button class="account-order-open" type="button" data-order-id="${esc(o.id)}">VER DETALHES</button></article>`).join('')||'<div class="account-empty">Nenhum pedido encontrado nesta conta.</div>';box.querySelectorAll('[data-order-id]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await openOrder(b.dataset.orderId)}catch(e){alert(e.message)}finally{b.disabled=false}})}
async function load(){const s=await fetch('/api/auth/session',{cache:'no-store'}).then(r=>r.json());if(!s.authenticated)return;document.getElementById('account-login').hidden=true;document.getElementById('account-content').hidden=false;document.getElementById('account-title').textContent='Minha conta';document.getElementById('account-subtitle').textContent='Gerencie seus dados, segurança e pedidos.';const logout=document.getElementById('account-logout');logout.hidden=false;logout.onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.reload()};setupSections();await Promise.all([loadProfile(),loadOrders()])}
document.addEventListener('DOMContentLoaded',()=>{setupLogin();document.querySelectorAll('.password-toggle').forEach(b=>b.onclick=()=>{const i=b.parentElement.querySelector('input');i.type=i.type==='password'?'text':'password'});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOrder()});setTimeout(load,400)})
})();

