(function(){
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const brl=c=>(Number(c||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const statusNames={aguardando_pagamento:'Aguardando pagamento',pago:'Pagamento aprovado',em_producao:'Em produção',pronto:'Pronto para envio',enviado:'Enviado',entregue:'Entregue',cancelado:'Cancelado',reembolsado:'Reembolsado'};
const statusName=s=>statusNames[s]||String(s||'—').replaceAll('_',' ');
const safeUrl=value=>{try{const u=new URL(String(value||''));return u.protocol==='https:'?u.href:''}catch{return''}};
let cfg=null,widgets=new Map();
async function turnstileConfig(){return cfg||(cfg=await fetch('/api/turnstile-config',{cache:'no-store'}).then(r=>r.json()).catch(()=>({enabled:false})))}
async function renderTurnstile(form){if(!form)return;const c=await turnstileConfig(),slot=form.querySelector('.account-turnstile');if(!c.enabled||!slot||widgets.has(form))return;for(let i=0;i<40&&!window.turnstile;i++)await new Promise(r=>setTimeout(r,100));if(window.turnstile)widgets.set(form,turnstile.render(slot,{sitekey:c.sitekey,theme:'light'}))}
function token(form){const id=widgets.get(form);return id!==undefined&&window.turnstile?turnstile.getResponse(id):''}
function reset(form){const id=widgets.get(form);if(id!==undefined&&window.turnstile)turnstile.reset(id)}
async function request(form,path,data,method='POST'){const out=form.querySelector('.account-feedback'),button=form.querySelector('[type=submit]');out.textContent='';button.disabled=true;try{const r=await fetch(path,{method,headers:{'content-type':'application/json'},body:JSON.stringify({...data,turnstileToken:token(form)})}),raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw new Error('O servidor não conseguiu concluir a operação.')}if(!r.ok)throw new Error(d.message||'Não foi possível continuar.');out.style.color='#08752b';out.textContent=d.message||'Concluído.';return d}catch(e){out.style.color='#a40000';out.textContent=e.message;reset(form);return null}finally{button.disabled=false}}
function setupLogin(){const f=document.getElementById('email-login-form');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const x=new FormData(f),d=await request(f,'/api/auth/login',{email:x.get('email'),password:x.get('password')});if(d)location.reload()};renderTurnstile(f)}
function showSection(name){document.querySelectorAll('.account-section').forEach(s=>s.hidden=s.id!==`account-section-${name}`);document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===name))}
function setupSections(){document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>showSection(b.dataset.section))}
async function loadProfile(){const r=await fetch('/api/account/profile',{cache:'no-store'}),d=await r.json();if(!r.ok)return;const p=d.profile,f=document.getElementById('profile-form'),a=p.address||{};for(const[k,v]of Object.entries({name:p.name,email:p.email,phone:p.phone,cpf:p.cpf,cep:a.cep,street:a.street,number:a.number,complement:a.complement,district:a.district,city:a.city,state:a.state}))if(f.elements[k])f.elements[k].value=v||'';const ef=document.getElementById('email-change-form');if(!d.emailServiceEnabled){ef.querySelector('button').disabled=true;ef.querySelector('.account-feedback').textContent='A confirmação por e-mail será liberada após configurar o serviço de envio.'}f.onsubmit=async e=>{e.preventDefault();const x=new FormData(f);await request(f,'/api/account/profile',{name:x.get('name'),phone:x.get('phone'),address:{cep:x.get('cep'),street:x.get('street'),number:x.get('number'),complement:x.get('complement'),district:x.get('district'),city:x.get('city'),state:x.get('state')}},'PATCH')};ef.onsubmit=async e=>{e.preventDefault();const x=new FormData(ef);await request(ef,'/api/account/email-change',{newEmail:x.get('newEmail'),currentPassword:x.get('currentPassword')})};renderTurnstile(ef);const pf=document.getElementById('password-form');pf.onsubmit=async e=>{e.preventDefault();const x=new FormData(pf);if(x.get('newPassword')!==x.get('confirmPassword'))return pf.querySelector('.account-feedback').textContent='As novas senhas não coincidem.';const d=await request(pf,'/api/account/password',{currentPassword:x.get('currentPassword'),newPassword:x.get('newPassword')});if(d)pf.reset()};renderTurnstile(pf)}
function closeOrder(){document.querySelector('.account-modal')?.remove()}
function row(label,value){return `<div class="account-detail-row"><span>${esc(label)}</span><strong>${esc(value??'—')}</strong></div>`}
function safeImage(value){if(!value)return'';try{const u=new URL(String(value),location.origin);return u.protocol==='https:'&&u.origin===location.origin||u.protocol==='https:'?u.href:''}catch{return''}}
function addressText(delivery={}){return [[delivery.endereco,delivery.numero].filter(Boolean).join(', '),delivery.complemento,delivery.bairro,[delivery.cidade,delivery.estado].filter(Boolean).join(' - '),delivery.cep?`CEP ${delivery.cep}`:''].filter(Boolean).join(' · ')||'Endereço não informado'}
function paymentName(value){const names={pix:'PIX',cartao:'Cartão',cartao_credito:'Cartão de crédito',boleto:'Boleto',dinheiro:'Dinheiro',pendente:'Pendente',aprovado:'Aprovado',aprovado_manual:'Aprovado'};return names[String(value||'').toLowerCase()]||String(value||'Não informado').replaceAll('_',' ')}
function itemDetails(item){const source={...(item.snapshot||{}),...(item.data||{}),...(item.details||{})};const keys=[['modelo','Modelo'],['tecido','Tecido'],['cor','Cor'],['forro','Forro'],['larguraAmbiente','Largura do ambiente'],['largura','Largura'],['altura','Altura'],['franzimento','Franzimento'],['consumoTecido','Consumo de tecido'],['barra','Barra']];return keys.map(([key,label])=>{let value=source[key];if(value===undefined||value===null||value==='')return'';if(['larguraAmbiente','largura','altura','consumoTecido'].includes(key)&&!String(value).includes('m'))value=String(value).replace('.',',')+' m';if(key==='franzimento'&&!String(value).includes('x'))value=String(value).replace('.',',')+'x';if(key==='barra'&&!String(value).includes('cm'))value=String(value)+' cm';return `<span><b>${esc(label)}:</b> ${esc(value)}</span>`}).join('')}
function orderTimeline(order,events=[]){
  const steps=['aguardando_pagamento','pago','em_producao','pronto','enviado','entregue'];
  const current=steps.indexOf(order.status),exception=['cancelado','reembolsado'].includes(order.status);
  const dates={aguardando_pagamento:order.created_at};
  for(const event of events){let status=event.toStatus;if(!status&&event.type==='order_created')status='aguardando_pagamento';if(!status&&event.type==='payment_approved')status='pago';if(!status&&event.type==='shipping_updated'&&current>=4)status='enviado';if(status&&!dates[status])dates[status]=event.createdAt}
  const normal=steps.map((status,index)=>{const done=!exception&&current>=index,active=!exception&&current===index,date=dates[status]?new Date(dates[status]).toLocaleString('pt-BR'):'';return `<li class="${done?'done ':''}${active?'active':''}"><i aria-hidden="true"></i><div><strong>${esc(statusName(status))}</strong>${date?`<span>${esc(date)}</span>`:done?'<span>Etapa concluída</span>':'<span>Aguardando</span>'}</div></li>`}).join('');
  const exceptional=exception?`<div class="account-timeline-exception"><strong>${esc(statusName(order.status))}</strong><span>${dates[order.status]?esc(new Date(dates[order.status]).toLocaleString('pt-BR')):'Consulte os detalhes com o atendimento.'}</span></div>`:'';
  return `<section class="account-timeline"><h3>Andamento do pedido</h3><ol>${normal}</ol>${exceptional}</section>`;
}
async function openOrder(id){
  const r=await fetch(`/api/account/order/${encodeURIComponent(id)}`,{cache:'no-store'}),d=await r.json();
  if(!r.ok)throw new Error(d.message||'Não foi possível abrir o pedido.');
  const o=d.order,f=o.freight||{},p=o.payment||{},url=safeUrl(f.trackingUrl);
  const items=(d.items||[]).map(i=>{const image=safeImage(i.image),qty=Number(i.quantity||1);return `<article class="account-product"><div class="account-product-main">${image?`<img src="${esc(image)}" alt="${esc(i.name)}" loading="lazy">`:'<div class="account-product-placeholder">SALVATEX</div>'}<div><strong>${esc(i.name)}</strong><small>${esc(i.category_name||i.category||'')}</small><div class="account-product-details">${itemDetails(i)}</div></div></div><div class="account-product-price"><span>${qty} × ${brl(i.unit_price_cents)}</span><strong>${brl(i.total_cents)}</strong></div></article>`}).join('');
  const tracking=o.status==='enviado'||o.status==='entregue'||f.trackingCode?`<section class="account-tracking-card"><h3>Rastreamento</h3>${row('Transportadora',f.carrier)}${row('Código de rastreio',f.trackingCode)}${url?`<a class="account-tracking-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">ACOMPANHAR ENTREGA</a>`:''}</section>`:`<section class="account-tracking-card account-tracking-pending"><h3>Rastreamento</h3><p>O código e o link aparecerão aqui assim que o pedido for enviado.</p></section>`;
  const docs=(d.invoices||[]).map(x=>`<a class="account-doc" href="/api/account/document?orderId=${encodeURIComponent(o.id)}&key=${encodeURIComponent(x.key)}">${esc(x.name||'Documento')}</a>`).join('');
  const freightValue=o.freight_cents===null||o.freight_cents===undefined?(f.gratis?'Grátis':'A calcular'):brl(o.freight_cents);
  const discount=Number(o.discount_cents||0);
  const modal=document.createElement('div');modal.className='account-modal';
  modal.innerHTML=`<div class="account-modal-card account-order-detail" role="dialog" aria-modal="true" aria-labelledby="account-order-title"><button class="account-modal-close" type="button" aria-label="Fechar">×</button><span class="account-modal-kicker">PEDIDO</span><h2 id="account-order-title">${esc(o.order_number)}</h2><div class="account-order-status account-status-${esc(o.status)}">${esc(statusName(o.status))}</div>${orderTimeline(o,d.timeline||[])}${tracking}<div class="account-order-summary"><section><h3>Detalhes do pedido</h3>${row('Data',new Date(o.created_at).toLocaleDateString('pt-BR'))}${row('Status',statusName(o.status))}${row('Pagamento',paymentName(p.status))}${row('Forma de pagamento',paymentName(p.forma))}${row('Frete',freightValue)}<div class="account-address"><span>Endereço de entrega</span><strong>${esc(addressText(o.delivery))}</strong></div></section><section class="account-order-products"><h3>Produtos</h3>${items||'<p>Nenhum item encontrado.</p>'}<div class="account-totals">${row('Subtotal',brl(o.subtotal_cents))}${row('Frete',freightValue)}${discount>0?row('Desconto','- '+brl(discount)):''}<div class="account-total-final"><span>Total</span><strong>${brl(o.total_cents)}</strong></div></div></section></div>${docs?`<section class="account-documents"><h3>Documentos</h3>${docs}</section>`:''}</div>`;
  modal.querySelector('.account-modal-close').onclick=closeOrder;modal.onclick=e=>{if(e.target===modal)closeOrder()};document.body.appendChild(modal);modal.querySelector('.account-modal-close').focus();
}
async function loadOrders(){const box=document.getElementById('account-orders'),r=await fetch('/api/account/orders',{cache:'no-store'}),d=await r.json();if(!r.ok){box.innerHTML=`<div class="account-empty">${esc(d.message||'Não foi possível carregar os pedidos.')}</div>`;return}box.innerHTML=(d.orders||[]).map(o=>`<article class="account-order"><div><span>Pedido</span><strong>${esc(o.order_number)}</strong><small>${new Date(o.created_at).toLocaleDateString('pt-BR')}</small></div><div><span>Status</span><strong class="account-status-text">${esc(statusName(o.status))}</strong></div><div><span>Total</span><strong>${brl(o.total_cents)}</strong></div><button class="account-order-open" type="button" data-order-id="${esc(o.id)}">VER DETALHES</button></article>`).join('')||'<div class="account-empty">Nenhum pedido encontrado nesta conta.</div>';box.querySelectorAll('[data-order-id]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await openOrder(b.dataset.orderId)}catch(e){alert(e.message)}finally{b.disabled=false}})}
async function load(){const s=await fetch('/api/auth/session',{cache:'no-store'}).then(r=>r.json());if(!s.authenticated)return;document.getElementById('account-login').hidden=true;document.getElementById('account-content').hidden=false;document.getElementById('account-title').textContent='Minha conta';document.getElementById('account-subtitle').textContent='Gerencie seus dados, segurança e pedidos.';const logout=document.getElementById('account-logout');logout.hidden=false;logout.onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.reload()};setupSections();await Promise.all([loadProfile(),loadOrders()])}
document.addEventListener('DOMContentLoaded',()=>{setupLogin();document.querySelectorAll('.password-toggle').forEach(b=>b.onclick=()=>{const i=b.parentElement.querySelector('input');i.type=i.type==='password'?'text':'password'});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOrder()});setTimeout(load,400)})
})();

