(function(){
const brl=c=>(Number(c||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),status=s=>({aguardando_pagamento:'Aguardando pagamento',pago:'Pago',em_producao:'Em produção',pronto:'Pronto',enviado:'Enviado',entregue:'Entregue',cancelado:'Cancelado',reembolsado:'Reembolsado'}[s]||s);
let turnstileConfig=null,widgets=new Map();
async function getTurnstile(){if(turnstileConfig)return turnstileConfig;turnstileConfig=await fetch('/api/turnstile-config',{cache:'no-store'}).then(r=>r.json()).catch(()=>({enabled:false}));return turnstileConfig}
async function renderTurnstile(form){const cfg=await getTurnstile();if(!cfg.enabled)return;const slot=form.querySelector('.account-turnstile');if(!slot||widgets.has(form))return;for(let i=0;i<40&&!window.turnstile;i++)await new Promise(r=>setTimeout(r,100));if(window.turnstile)widgets.set(form,turnstile.render(slot,{sitekey:cfg.sitekey,theme:'light'}))}
function token(form){const id=widgets.get(form);return id!==undefined&&window.turnstile?turnstile.getResponse(id):''}
function reset(form){const id=widgets.get(form);if(id!==undefined&&window.turnstile)turnstile.reset(id)}
function tabs(){document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));const register=b.dataset.authTab==='register';document.getElementById('email-login-form').hidden=register;document.getElementById('email-register-form').hidden=!register;document.getElementById('account-title').textContent=register?'Criar uma conta':'Iniciar sessão';document.getElementById('account-subtitle').textContent=register?'Compre mais rápido e acompanhe seus pedidos em um só lugar.':'Entre para acompanhar pedidos, rastreio e documentos.';renderTurnstile(register?document.getElementById('email-register-form'):document.getElementById('email-login-form'))})}
async function submit(form,path,data){const out=form.querySelector('.account-feedback'),button=form.querySelector('[type=submit]');out.textContent='';button.disabled=true;try{const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...data,turnstileToken:token(form)})}),raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw new Error('O servidor não conseguiu concluir o cadastro. Tente novamente.')}if(!r.ok)throw new Error(d.message||'Não foi possível continuar.');location.reload()}catch(e){out.textContent=e.message;reset(form)}finally{button.disabled=false}}
function forms(){const login=document.getElementById('email-login-form'),register=document.getElementById('email-register-form');login.onsubmit=e=>{e.preventDefault();const f=new FormData(login);submit(login,'/api/auth/login',{email:f.get('email'),password:f.get('password')})};register.onsubmit=e=>{e.preventDefault();const f=new FormData(register);if(f.get('password')!==f.get('confirmPassword')){register.querySelector('.account-feedback').textContent='As senhas não coincidem.';return}submit(register,'/api/auth/register',{name:f.get('name'),email:f.get('email'),phone:f.get('phone'),password:f.get('password')})};document.querySelectorAll('.password-toggle').forEach(b=>b.onclick=()=>{const i=b.parentElement.querySelector('input');i.type=i.type==='password'?'text':'password';b.setAttribute('aria-label',i.type==='password'?'Mostrar senha':'Ocultar senha')});renderTurnstile(login)}
async function load(){const s=await fetch('/api/auth/session',{cache:'no-store'}).then(r=>r.json());if(!s.authenticated)return;document.getElementById('account-login').hidden=true;document.getElementById('account-content').hidden=false;document.getElementById('account-title').textContent='Meus pedidos';document.getElementById('account-subtitle').textContent='Acompanhe pedidos, rastreio e documentos.';const logout=document.getElementById('account-logout');logout.hidden=false;logout.onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.reload()};document.getElementById('account-user').innerHTML=`<strong>${esc(s.user.name||'')}</strong><span>${esc(s.user.email)}</span>`;const d=await fetch('/api/account/orders',{cache:'no-store'}).then(r=>r.json());document.getElementById('account-orders').innerHTML=(d.orders||[]).map(o=>`<article class="account-order"><div><span>Pedido</span><strong>${esc(o.order_number)}</strong><small>${new Date(o.created_at).toLocaleDateString('pt-BR')}</small></div><div><span>Status</span><strong>${esc(status(o.status))}</strong>${o.freight?.trackingCode?`<small>Rastreio: ${esc(o.freight.trackingCode)}</small>`:''}</div><div><span>Total</span><strong>${brl(o.total_cents)}</strong></div><button data-order="${esc(o.id)}" class="ghost-btn">Detalhes</button></article>`).join('')||'<div class="account-empty">Nenhum pedido encontrado nesta conta.</div>';document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>open(b.dataset.order))}
async function open(id){const r=await fetch('/api/account/order/'+encodeURIComponent(id),{cache:'no-store'}),d=await r.json();if(!r.ok)return alert(d.message||'Erro');let m=document.getElementById('account-modal');if(!m){m=document.createElement('div');m.id='account-modal';m.className='account-modal';document.body.appendChild(m)}const o=d.order;m.innerHTML=`<div class="account-modal-card"><button class="account-modal-close">×</button><h2>${esc(o.order_number)}</h2><p><b>Status:</b> ${esc(status(o.status))}</p>${o.freight?.trackingCode?`<p><b>Rastreio:</b> ${esc(o.freight.trackingCode)}</p>`:''}<h3>Itens</h3>${(d.items||[]).map(i=>`<div class="account-item"><span>${esc(i.name)} × ${i.quantity}</span><strong>${brl(i.total_cents)}</strong></div>`).join('')}<h3>Nota fiscal</h3>${(d.invoices||[]).map(n=>`<a class="account-doc" href="/api/account/document?orderId=${encodeURIComponent(id)}&key=${encodeURIComponent(n.key)}">${esc(n.name||'Nota fiscal')}</a>`).join('')||'<p>Ainda não anexada.</p>'}</div>`;m.querySelector('.account-modal-close').onclick=()=>m.remove()}
document.addEventListener('DOMContentLoaded',()=>{tabs();forms();setTimeout(load,500)})})();

