const brlPagina=cents=>(Number(cents||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const escPagina=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function contadorPagina(){const el=document.getElementById('contador-carrinho');if(!el)return;try{const c=JSON.parse(localStorage.getItem('salvatexCarrinho')||'[]');const q=Array.isArray(c)?c.reduce((s,i)=>s+Number(i.quantidade||1),0):0;el.textContent=q;el.style.display=q?'flex':'none'}catch{el.style.display='none'}}
function tipoProduto(p){return p.saleType==='sob_medida'?'Sob medida':p.saleType==='pronta_entrega'?'Pronta entrega':'Produto'}
function cardPagina(p){const preco=p.basePriceCents>0?brlPagina(p.basePriceCents):'Consulte';const parcelas=p.basePriceCents>0?`<div class="collection-installment">10x de ${brlPagina(p.basePriceCents/10)} sem juros</div>`:'';return `<article class="collection-card" data-product-id="${escPagina(p.id)}"><a class="collection-image" href="produto.html?slug=${encodeURIComponent(p.slug)}">${p.imageUrl?`<img src="${escPagina(p.imageUrl)}" alt="${escPagina(p.name)}" loading="lazy">`:'<div class="collection-placeholder">SALVATEX</div>'}</a><div class="collection-card-body"><div class="collection-type">${escPagina(p.categoryName||tipoProduto(p))}</div><h2><a href="produto.html?slug=${encodeURIComponent(p.slug)}">${escPagina(p.name)}</a></h2><div class="collection-price">${preco}</div>${parcelas}<a class="collection-link" href="produto.html?slug=${encodeURIComponent(p.slug)}">Ver produto <span>›</span></a></div></article>`}
function measureMenu(page,products){const ms=Array.isArray(page.measures)?page.measures:[];if(!ms.length)return '';return `<div class="measure-filter"><button type="button" class="measure-filter-toggle" id="measure-toggle"><span id="measure-current">Medidas pré-definidas</span><span>⌄</span></button><div class="measure-filter-menu" id="measure-menu"><div class="measure-filter-title">Medidas Pré Definidas:</div>${ms.map(m=>`<button type="button" class="measure-filter-option" data-measure-id="${escPagina(m.id)}">${escPagina(m.label)}</button>`).join('')}${page.customMeasureUrl?`<a class="measure-filter-custom" href="${escPagina(page.customMeasureUrl)}">Tenho uma medida específica</a>`:''}</div></div>`}
function bindMeasures(page,products){const toggle=document.getElementById('measure-toggle'),menu=document.getElementById('measure-menu'),current=document.getElementById('measure-current'),grid=document.getElementById('collection-grid');if(!toggle||!menu||!grid)return;const aplicarMedida=(id)=>{const m=(page.measures||[]).find(x=>String(x.id)===String(id));if(!m)return false;const ids=new Set(Array.isArray(m.productIds)?m.productIds.map(String):[]);const filtered=ids.size?products.filter(p=>ids.has(String(p.id))):[];current.textContent=m.value||m.label;grid.innerHTML=filtered.length?filtered.map(cardPagina).join(''):'<div class="catalog-empty">Nenhum produto vinculado a esta medida.</div>';menu.classList.remove('open');menu.querySelectorAll('.measure-filter-option').forEach(x=>x.classList.toggle('active',String(x.dataset.measureId)===String(m.id)));return true};toggle.onclick=()=>menu.classList.toggle('open');document.addEventListener('click',e=>{if(!e.target.closest('.measure-filter'))menu.classList.remove('open')});menu.querySelectorAll('[data-measure-id]').forEach(btn=>btn.onclick=()=>aplicarMedida(btn.dataset.measureId));const medidaUrl=new URLSearchParams(location.search).get('medida');if(medidaUrl)aplicarMedida(medidaUrl)}
async function carregarPagina(){const view=document.getElementById('page-view'),slug=new URLSearchParams(location.search).get('slug');if(!slug){view.innerHTML='<div class="catalog-empty">Página não informada.</div>';return}try{const r=await fetch('/api/pages/'+encodeURIComponent(slug),{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Página não encontrada');const p=d.page;
const destinos={
  configurador_wave:'configurador.html?id=wave',
  configurador_prega_macho:'configurador.html?id=prega-macho',
  configurador_ilhos:'configurador.html?id=cortina-varao',
  configurador_persiana:'configurador-persiana.html?id=persiana'
};
if(destinos[p.pageType]){
  location.replace(destinos[p.pageType]);
  return;
}
document.title=(p.seoTitle||p.title)+' | Salvatex';const meta=document.querySelector('meta[name="description"]');if(meta&&p.seoDescription)meta.content=p.seoDescription;if(p.pageType==='produtos'){view.innerHTML=`<section class="collection-head">${p.heroImageUrl?`<div class="collection-hero"><img src="${escPagina(p.heroImageUrl)}" alt=""></div>`:''}<div class="collection-head-row"><div><div class="collection-kicker">SALVATEX CORTINAS</div><h1>${escPagina(p.title)}</h1></div>${measureMenu(p,d.products)}</div></section><section class="collection-grid" id="collection-grid">${d.products.length?d.products.map(cardPagina).join(''):'<div class="catalog-empty">Nenhum produto publicado nesta página.</div>'}</section>`;bindMeasures(p,d.products)}else{view.innerHTML=`<article class="content-page"><div class="collection-kicker">SALVATEX CORTINAS</div><h1>${escPagina(p.title)}</h1><div class="content-page-body">${p.contentHtml||''}</div></article>`}}catch(e){view.innerHTML=`<div class="catalog-empty">${escPagina(e.message)}</div>`}}
document.addEventListener('DOMContentLoaded',()=>{contadorPagina();carregarPagina()});
