(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const page=document.documentElement.dataset.tenantPage||'';let widget=null,turnCfg={enabled:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=c=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(c||0)/100);
function statusName(v){const m={aguardando_pagamento:'Aguardando pagamento',pago:'Pago',em_producao:'Em produção',pronto:'Pronto',enviado:'Enviado',entregue:'Entregue',cancelado:'Cancelado',reembolsado:'Reembolsado'};return m[v]||String(v||'—').replaceAll('_',' ')}
async function json(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...opt}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Não foi possível continuar.');return d}
async function identity(){try{const [a,b]=await Promise.all([json('/api/store-config'),json('/api/layout')]);const cfg=a.config||{},layout=b.layout||{},name=String(cfg.storeName||cfg.name||location.hostname.split('.')[0]||'Loja').trim();$$('[data-brand]').forEach(x=>x.textContent=name.toUpperCase());$$('[data-footer-brand]').forEach(x=>x.textContent=name.toUpperCase());const primary=layout?.branding?.colors?.primary||layout?.colors?.primary||cfg.primaryColor;if(primary)document.documentElement.style.setProperty('--brand',primary);const accent=layout?.branding?.colors?.accent||layout?.colors?.accent||cfg.accentColor;if(accent)document.documentElement.style.setProperty('--accent',accent);document.title=document.title.includes('—')?document.title:`${document.title} — ${name}`}catch{}}
function feedback(text,ok=false){const el=$('#feedback');if(!el)return;el.textContent=text||'';el.className='feedback '+(text?(ok?'ok':'error'):'')}
async function setupTurnstile(){try{turnCfg=await json('/api/turnstile-config');}catch{return}if(!turnCfg.enabled)return;for(let i=0;i<50&&!window.turnstile;i++)await new Promise(r=>setTimeout(r,100));const slot=$('#turnstile-slot');if(window.turnstile&&slot)widget=window.turnstile.render(slot,{sitekey:turnCfg.sitekey,theme:'light'})}
function token(){return widget!==null&&window.turnstile?window.turnstile.getResponse(widget):''}
function resetTurnstile(){if(widget!==null&&window.turnstile)window.turnstile.reset(widget)}
async function post(path,body){try{return await json(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,turnstileToken:token()})})}catch(e){resetTurnstile();throw e}}
function google(){const b=$('#google-login');if(b)b.onclick=()=>{const returnTo=page==='register'?'/minha-conta.html':location.pathname+location.search;location.href='/api/auth/google/start?return_to='+encodeURIComponent(returnTo)}}
async function account(){const s=await json('/api/auth/session');if(!s.authenticated)return;$('#auth-area').hidden=true;$('#account-area').hidden=false;$('#hello').textContent=`Olá, ${s.user?.name||s.user?.email||'cliente'}`;$('#logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST',credentials:'same-origin'});location.reload()};try{const d=await json('/api/account/orders'),orders=d.orders||[];$('#orders').innerHTML=orders.length?orders.map(o=>`<article class="order"><div><small class="muted">Pedido</small><strong style="display:block">${esc(o.order_number)}</strong><small class="muted">${new Date(o.created_at).toLocaleDateString('pt-BR')}</small></div><div><small class="muted">Status</small><span class="badge">${esc(statusName(o.status))}</span></div><div><small class="muted">Total</small><strong style="display:block">${money(o.total_cents)}</strong></div><div><small class="muted">Atualizado</small><span>${o.updated_at?new Date(o.updated_at).toLocaleDateString('pt-BR'):'—'}</span></div></article>`).join(''):'<p class="muted">Nenhum pedido encontrado nesta loja.</p>'}catch(e){$('#orders').innerHTML=`<p class="feedback error">${esc(e.message)}</p>`}}
async function boot(){await identity();await setupTurnstile();google();if(page==='account'){const f=$('#login-form');f.onsubmit=async e=>{e.preventDefault();feedback('');const b=f.querySelector('[type=submit]');b.disabled=true;try{const fd=new FormData(f);await post('/api/auth/login',{email:fd.get('email'),password:fd.get('password')});location.reload()}catch(err){feedback(err.message)}finally{b.disabled=false}};await account();}
if(page==='register'){const f=$('#register-form');f.onsubmit=async e=>{e.preventDefault();feedback('');const fd=new FormData(f),password=String(fd.get('password')||'');if(password!==String(fd.get('confirmPassword')||'')){feedback('As senhas não coincidem.');return}const b=f.querySelector('[type=submit]');b.disabled=true;try{await post('/api/auth/register',{name:fd.get('name'),email:fd.get('email'),phone:fd.get('phone'),password});location.href='/minha-conta.html'}catch(err){feedback(err.message)}finally{b.disabled=false}}}
if(page==='forgot'){const f=$('#forgot-form');f.onsubmit=async e=>{e.preventDefault();feedback('');const b=f.querySelector('[type=submit]');b.disabled=true;try{const fd=new FormData(f),d=await post('/api/auth/forgot-password',{email:fd.get('email')});feedback(d.message||'Se a conta existir, enviaremos as instruções.',true)}catch(err){feedback(err.message)}finally{b.disabled=false}}}
if(page==='reset'){const f=$('#reset-form'),resetToken=new URL(location.href).searchParams.get('token')||'';if(!resetToken)feedback('Link de redefinição inválido ou incompleto.');f.onsubmit=async e=>{e.preventDefault();feedback('');const fd=new FormData(f),password=String(fd.get('password')||'');if(password!==String(fd.get('confirmPassword')||'')){feedback('As senhas não coincidem.');return}const b=f.querySelector('[type=submit]');b.disabled=true;try{const d=await post('/api/auth/reset-password',{token:resetToken,password});feedback(d.message||'Senha redefinida.',true);setTimeout(()=>location.href='/minha-conta.html',900)}catch(err){feedback(err.message)}finally{b.disabled=false}}}}
boot().catch(e=>feedback(e.message));
})();