import { json, requireAdmin, clean, sanitizeHtml, slugify, logAdmin } from "../_auth.js";
import { ensurePageNavigationSchema,normalizeNavGroup,normalizeExternalUrl,normalizePageType,legacyConfiguratorId } from '../../../api/_page-schema.js';
function normalizeProductIds(value){if(!Array.isArray(value))return[];return[...new Set(value.map(v=>clean(v,160)).filter(Boolean))].slice(0,100)}
function normalizeMeasures(value){if(!Array.isArray(value))return[];return value.slice(0,30).map((m,index)=>({id:clean(m?.id,80)||`medida-${index+1}`,label:clean(m?.label,160),value:clean(m?.value,80),productIds:normalizeProductIds(m?.productIds)})).filter(m=>m.label)}
async function configuratorAllowed(db,storeId){const row=await db.prepare(`SELECT pf.enabled FROM platform_company_stores pcs JOIN platform_features pf ON pf.company_id=pcs.company_id AND pf.feature_key='configurator' WHERE pcs.store_id=?1 LIMIT 1`).bind(storeId).first();return Number(row?.enabled)===1}
async function uniqueSlug(db,storeId,value,id){const base=slugify(value)||`pagina-${String(id).slice(0,8)}`;for(let i=0;i<50;i++){const candidate=i?`${base}-${i+1}`:base;const row=await db.prepare('SELECT id FROM pages WHERE store_id=?1 AND slug=?2 AND id<>?3 LIMIT 1').bind(storeId,candidate,id).first();if(!row)return candidate}return`${base}-${crypto.randomUUID().slice(0,8)}`}
function requestedConfiguratorId(body){return clean(body.configuratorId||legacyConfiguratorId(body.pageType),80)}
export async function onRequestPut(context){
  const a=await requireAdmin(context);if(!a.ok)return a.response;const storeId=a.storeId,id=String(context.params.id||''),requestId=crypto.randomUUID().slice(0,10);await ensurePageNavigationSchema(context.env.DB);const exists=await context.env.DB.prepare('SELECT id FROM pages WHERE id=?1 AND store_id=?2 LIMIT 1').bind(id,storeId).first();if(!exists)return json({ok:false,message:'Página não encontrada.'},404);
  let b={};try{b=await context.request.json()}catch{return json({ok:false,message:'JSON inválido.'},400)}const title=clean(b.title,240);if(!title)return json({ok:false,message:'Título obrigatório.'},400);const pageType=normalizePageType(b.pageType),configuratorId=requestedConfiguratorId(b);
  if(pageType==='configurador'){if(!await configuratorAllowed(context.env.DB,storeId))return json({ok:false,code:'FEATURE_NOT_ENABLED',message:'O configurador não está liberado para esta empresa.'},403);if(!configuratorId)return json({ok:false,message:'Selecione qual configurador esta página deve abrir.'},422)}
  const externalUrl=normalizeExternalUrl(b.externalUrl||b.customMeasureUrl);if(pageType==='link'&&!externalUrl)return json({ok:false,message:'Informe o destino do link.'},422);
  const productIds=pageType==='produtos'?normalizeProductIds(b.productIds):[],measures=pageType==='produtos'?normalizeMeasures(b.measures):[],slug=await uniqueSlug(context.env.DB,storeId,b.slug||title,id),now=new Date().toISOString();
  if(productIds.length){const placeholders=productIds.map((_,i)=>`?${i+2}`).join(',');const found=await context.env.DB.prepare(`SELECT id FROM products WHERE store_id=?1 AND id IN (${placeholders})`).bind(storeId,...productIds).all();const valid=new Set((found.results||[]).map(x=>x.id));if(productIds.some(pid=>!valid.has(pid)))return json({ok:false,message:'Há produtos selecionados que não pertencem a esta loja.'},422)}
  try{await context.env.DB.prepare(`UPDATE pages SET title=?1,slug=?2,content_html=?3,seo_title=?4,seo_description=?5,active=?6,page_type=?7,product_ids_json=?8,hero_image_url=?9,measures_json=?10,custom_measure_url=?11,nav_group=?12,nav_order=?13,menu_label=?14,external_url=?15,nav_parent_id=?16,configurator_id=?17,updated_at=?18 WHERE id=?19 AND store_id=?20`).bind(title,slug,pageType==='conteudo'?sanitizeHtml(b.contentHtml):'',clean(b.seoTitle,240),clean(b.seoDescription,500),b.active===false?0:1,pageType,JSON.stringify(productIds),clean(b.heroImageUrl,1000)||null,JSON.stringify(measures),pageType==='produtos'?clean(b.customMeasureUrl,1000)||null:null,normalizeNavGroup(b.navGroup||'oculto'),Number.isFinite(Number(b.navOrder))?Math.round(Number(b.navOrder)):100,clean(b.menuLabel,120)||title,externalUrl||null,clean(b.navParentId,160)||null,pageType==='configurador'?configuratorId||null:null,now,id,storeId).run();await logAdmin(context.env.DB,'page_updated','page',id,{title,pageType,configuratorId,slug},storeId);return json({ok:true,slug})}catch(error){console.error('[page update]',requestId,storeId,String(error?.message||error));return json({ok:false,message:`Não foi possível atualizar a página. Referência: ${requestId}.`},500)}
}
export async function onRequestDelete(context){const a=await requireAdmin(context);if(!a.ok)return a.response;const storeId=a.storeId,id=String(context.params.id||'');await ensurePageNavigationSchema(context.env.DB);await context.env.DB.prepare('UPDATE pages SET nav_parent_id=NULL WHERE store_id=?1 AND nav_parent_id=?2').bind(storeId,id).run();await context.env.DB.prepare('DELETE FROM pages WHERE id=?1 AND store_id=?2').bind(id,storeId).run();await logAdmin(context.env.DB,'page_deleted','page',id,null,storeId);return json({ok:true})}
