(() => {
  const state = { session:null, company:null, domains:[], features:[] };
  const content = document.querySelector("#content");
  const escapeHtml = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const api = async (url, options={}) => { const r=await fetch(url,{credentials:"same-origin",headers:{accept:"application/json",...(options.headers||{})},...options}); const d=await r.json().catch(()=>({})); if(!r.ok) throw Object.assign(new Error(d.message||d.code||"Falha"),{status:r.status}); return d; };
  const card = (title,text,action="") => `<article class="card"><h3>${title}</h3><p>${text}</p>${action}</article>`;
  const overview = () => { const enabled=state.features.filter(x=>x.enabled).length; content.innerHTML=`<div class="welcome"><span>LOJA EM CONFIGURAÇÃO</span><h2>Olá, ${escapeHtml(state.session.user.name)}.</h2><p>Complete os passos abaixo para publicar sua loja.</p></div><div class="cards">${card("Identidade da loja","Adicione logotipo, cores e informações da empresa.",'<button data-go="design">Configurar layout</button>')}${card("Catálogo","Cadastre os primeiros produtos e categorias.",'<button data-go="catalog">Cadastrar produtos</button>')}${card("Domínio","Use o endereço gratuito ou conecte seu domínio.",'<button data-go="domains">Configurar domínio</button>')}${card("Recursos liberados",`${enabled} funcionalidades disponíveis no plano atual.`,'<button data-go="plan">Ver plano</button>')}</div>`; };
  const domains = () => { const rows=state.domains.map(d=>`<div class="domain-row"><div><strong>${escapeHtml(d.hostname)}</strong><small>${d.domain_type==="platform_subdomain"?"Endereço gratuito RADZ HUB":"Domínio próprio"}</small></div><span class="status ${escapeHtml(d.status)}">${escapeHtml(d.status)}</span></div>`).join(""); content.innerHTML=`<div class="page-head"><h2>Meu domínio</h2><p>Sua loja recebe um endereço gratuito. Você também poderá conectar um domínio comprado em qualquer provedor.</p></div><div class="panel">${rows||"Nenhum domínio cadastrado."}</div><div class="panel guide"><h3>Conectar domínio próprio</h3><ol><li>Informe o domínio que você já possui.</li><li>A RADZ HUB mostrará o registro DNS necessário.</li><li>Copie o registro no Registro.br ou no seu provedor.</li><li>Aguarde a verificação e a ativação automática do HTTPS.</li></ol><p class="note">A RADZ HUB nunca solicitará a senha do seu provedor de domínio.</p><button disabled>Adicionar domínio — disponível após ativação do radzhub.com.br</button></div>`; };
  const placeholder = (name,text) => { content.innerHTML=`<div class="page-head"><h2>${name}</h2><p>${text}</p></div><div class="empty">Esta área já está separada por empresa e será conectada aos módulos da loja na próxima ativação.</div>`; };
  const views={overview,domains,store:()=>placeholder("Minha loja","Informações públicas, endereço e situação da loja."),design:()=>placeholder("Layout","Logotipo, cores, fontes, banners e modelo visual."),catalog:()=>placeholder("Produtos","Catálogo exclusivo da sua empresa."),payments:()=>placeholder("Pagamentos","Provedores liberados pela RADZ HUB para sua empresa."),shipping:()=>placeholder("Fretes","Transportadoras e integrações disponíveis."),team:()=>placeholder("Equipe","Convide funcionários e defina permissões."),plan:()=>placeholder("Plano e taxas",`Plano ${escapeHtml(state.company.plan_code)} · taxa configurada de ${(state.company.platform_fee_basis_points/100).toFixed(2).replace(".",",")}%`)};
  const open = (name) => { document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===name)); document.querySelector("#title").textContent=document.querySelector(`nav button[data-view="${name}"]`)?.textContent||"Painel"; (views[name]||overview)(); };
  document.addEventListener("click",e=>{ const target=e.target.closest("[data-view],[data-go]"); if(target) open(target.dataset.view||target.dataset.go); });
  document.querySelector("#logout").addEventListener("click",async()=>{await api("/platform/api/session",{method:"DELETE"}).catch(()=>{}); location.assign("/platform/login.html");});
  (async()=>{ try { state.session=await api("/platform/api/session"); const details=await api("/platform/api/company"); state.company=details.company;state.domains=details.domains;state.features=details.features;document.querySelector("#company-name").textContent=state.company.trade_name;document.querySelector("#company-plan").textContent=`Plano ${state.company.plan_code}`;document.querySelector("#visit-store").href=`https://${state.company.slug}.radzhub.com.br`;document.querySelector("#loading").hidden=true;document.querySelector("#app").hidden=false;overview(); } catch(e){ if(e.status===401) location.replace("/platform/login.html"); else document.querySelector("#loading").textContent="A estrutura da plataforma ainda precisa ser ativada no banco."; } })();
})();


