import { json, logAdmin } from "../_auth.js";
import { requireFeature } from "../_features.js";

const IDS = new Set(["wave","prega-macho","cortina-varao","persiana"]);
const TENANT_CONFIG_VERSION=4;
function defaultLabels(id){const isBlind=id==="persiana";return{pickerTitle:"Configurador",kicker:"CONFIGURADOR",pageTitle:isBlind?"Configure sua persiana sob medida":"Configure seu produto sob medida",pageDescription:"Informe as medidas e escolha as opções disponíveis.",formTitle:"Configure seu produto",formSubtitle:"Escolha as características abaixo para calcular seu produto.",step1:"Produto",step2:"Material",step3:"Opção",step4:"Acabamento",step5:"Resumo",widthLabel:"Largura",heightLabel:"Altura",modelLabel:"Modelo",fabricLabel:"Material",liningLabel:"Opção",colorLabel:"Cor",trackLabel:"Acabamento",secondaryProductLabel:"Produto secundário",summaryTitle:"Resumo",addToCartLabel:"Adicionar ao carrinho"};}
function defaultConfigurator(id){const base={_tenantConfigVersion:TENANT_CONFIG_VERSION,id,nome:id==="prega-macho"?"Cortina Prega Macho":id==="cortina-varao"?"Cortina de Ilhós":id==="persiana"?"Persiana sob medida":"Cortina Wave",ativo:false,modelo:id==="prega-macho"?"Prega Macho":id==="cortina-varao"?"Ilhós":id==="persiana"?"Persiana":"Wave",tipo:id==="persiana"?"persiana":"cortina",descricao:"",modoCalculo:id==="persiana"?"area":"metro_tecido",labels:defaultLabels(id),medidas:{larguraMinima:.5,larguraMaxima:id==="persiana"?5:12,alturaMinima:.5,alturaEntradaMaxima:id==="persiana"?4:5,calculoMaximo:id==="persiana"?3.5:3.2,inicioAcrescimo:id==="persiana"?999:2.8,acrescimoPercentual:id==="persiana"?0:25,acimaMaximo:{modo:"consulta",texto:"Medida fora do limite automático. Solicite orçamento personalizado.",textoBotao:"Solicitar orçamento",permitirCarrinho:false}},barra:{faixas:[],acimaInicio:20},franzimentos:id==="persiana"?[]:[{valor:2,rotulo:"2x"},{valor:2.5,rotulo:"2,5x"},{valor:3,rotulo:"3x"}],tecidos:{},trilhos:{},persiana:{areaMinima:.6,acionamentos:[],ladosComando:["Direito","Esquerdo"],voltagens:["110V","220V","Bivolt"]},midia:[],estoqueCombinacoes:{}};return base;}
function mergeDeep(target,source){if(!source||typeof source!=="object"||Array.isArray(source))return target;for(const[k,v]of Object.entries(source)){if(v&&typeof v==="object"&&!Array.isArray(v))target[k]=mergeDeep(target[k]&&typeof target[k]==="object"&&!Array.isArray(target[k])?target[k]:{},v);else target[k]=v;}return target;}
function isSalvatex(store){return String(store?.slug||'').toLowerCase()==='salvatex';}
function canUseSavedConfig(saved,store){return isSalvatex(store)||Number(saved?._tenantConfigVersion||0)>=TENANT_CONFIG_VERSION;}
async function readConfig(db,storeId,id,store){const row=await db.prepare(`SELECT value_json,updated_at FROM store_configs WHERE store_id=?1 AND config_key=?2`).bind(storeId,'configurator_'+id.replaceAll('-','_')).first();if(row?.value_json){try{const saved=JSON.parse(row.value_json);if(canUseSavedConfig(saved,store)){const cfg=mergeDeep(defaultConfigurator(id),saved);for(const key of ['tecidos','trilhos','estoqueCombinacoes'])cfg[key]=saved[key]&&typeof saved[key]==='object'?saved[key]:{};cfg.midia=Array.isArray(saved.midia)?saved.midia:[];cfg.franzimentos=Array.isArray(saved.franzimentos)?saved.franzimentos:cfg.franzimentos;cfg._tenantConfigVersion=TENANT_CONFIG_VERSION;return{configurator:cfg,updatedAt:row.updated_at||null,source:'d1'};}return{configurator:defaultConfigurator(id),updatedAt:null,source:'tenant-v4-reset'};}catch{}}return{configurator:defaultConfigurator(id),updatedAt:null,source:'default'};}
async function authConfigurator(context){return requireFeature(context,'configurator');}
export async function onRequestGet(context){const auth=await authConfigurator(context);if(!auth.ok)return auth.response;const id=String(context.params.id||'').toLowerCase();if(!IDS.has(id))return json({ok:false,message:'Configurador não suportado.'},404);try{return json({ok:true,...await readConfig(context.env.DB,auth.storeId,id,auth.store)});}catch(error){console.error(error);return json({ok:false,message:'Não foi possível carregar o configurador.'},500)}}
export async function onRequestPut(context){const auth=await authConfigurator(context);if(!auth.ok)return auth.response;const storeId=auth.storeId,id=String(context.params.id||'').toLowerCase();if(!IDS.has(id))return json({ok:false,message:'Configurador não suportado.'},404);let body={};try{body=await context.request.json()}catch{return json({ok:false,message:'JSON inválido.'},400)}const received=(body.configurator&&typeof body.configurator==='object')?body.configurator:(body.wave&&typeof body.wave==='object'?body.wave:body);if(!received||typeof received!=='object'||Array.isArray(received))return json({ok:false,message:'Configurador inválido.'},400);const cfg=mergeDeep(defaultConfigurator(id),received);cfg.id=id;cfg._tenantConfigVersion=TENANT_CONFIG_VERSION;cfg.tecidos=received.tecidos&&typeof received.tecidos==='object'?received.tecidos:{};cfg.trilhos=received.trilhos&&typeof received.trilhos==='object'?received.trilhos:{};cfg.estoqueCombinacoes=received.estoqueCombinacoes&&typeof received.estoqueCombinacoes==='object'?received.estoqueCombinacoes:{};cfg.midia=Array.isArray(received.midia)?received.midia:[];if(Number(cfg.medidas?.calculoMaximo||0)<=0)return json({ok:false,message:'Informe o limite de cálculo automático.'},400);if(Number(cfg.medidas?.alturaEntradaMaxima||0)<Number(cfg.medidas?.calculoMaximo||0))return json({ok:false,message:'A altura máxima permitida não pode ser menor que o limite automático.'},400);const now=new Date().toISOString(),key='configurator_'+id.replaceAll('-','_');try{await context.env.DB.prepare(`INSERT INTO store_configs(store_id,config_key,value_json,updated_at) VALUES(?1,?2,?3,?4) ON CONFLICT(store_id,config_key) DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at`).bind(storeId,key,JSON.stringify(cfg),now).run();await logAdmin(context.env.DB,'configurator_updated','configurator',id,{nome:cfg.nome,updatedAt:now,tenantConfigVersion:TENANT_CONFIG_VERSION},storeId);return json({ok:true,configurator:cfg,wave:id==='wave'?cfg:undefined,updatedAt:now});}catch(error){console.error('save configurator',error);return json({ok:false,message:'Erro ao salvar o configurador no D1.'},500)}}
export async function onRequestDelete(context){const auth=await authConfigurator(context);if(!auth.ok)return auth.response;const storeId=auth.storeId,id=String(context.params.id||'').toLowerCase();if(!IDS.has(id))return json({ok:false,message:'Configurador não suportado.'},404);const key='configurator_'+id.replaceAll('-','_');try{await context.env.DB.prepare(`DELETE FROM store_configs WHERE store_id=?1 AND config_key=?2`).bind(storeId,key).run();await logAdmin(context.env.DB,'configurator_reset','configurator',id,{resetAt:new Date().toISOString()},storeId);return json({ok:true,configurator:defaultConfigurator(id)});}catch(error){console.error('reset configurator',error);return json({ok:false,message:'Erro ao redefinir o configurador.'},500)}}
export async function onRequestPost(context){return onRequestPut(context);}
