import { json, logAdmin } from "../_auth.js";
import { requireFeature } from "../_features.js";

const BUILT_INS=[
  {id:'wave',nome:'Cortina Wave',icon:'〰',tipo:'cortina'},
  {id:'prega-macho',nome:'Cortina Prega Macho',icon:'▥',tipo:'cortina'},
  {id:'cortina-varao',nome:'Cortina de Ilhós',icon:'━',tipo:'cortina'},
  {id:'persiana',nome:'Persiana sob medida',icon:'▤',tipo:'persiana'}
];
const VERSION=4;
const slugify=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48);
function generic(id,nome,tipo='cortina'){const blind=tipo==='persiana';return{_tenantConfigVersion:VERSION,id,nome:nome||'Novo configurador',ativo:false,modelo:nome||'Produto',tipo:blind?'persiana':'cortina',descricao:'',modoCalculo:blind?'area':'metro_tecido',labels:{pickerTitle:'Configurador',kicker:'CONFIGURADOR',pageTitle:'Configure seu produto sob medida',pageDescription:'Informe as medidas e escolha as opções disponíveis.',formTitle:'Configure seu produto',formSubtitle:'Escolha as características abaixo para calcular seu produto.',step1:'Produto',step2:'Material',step3:'Opção',step4:'Acabamento',step5:'Resumo',widthLabel:'Largura',heightLabel:'Altura',modelLabel:'Modelo',fabricLabel:'Material',liningLabel:'Opção',colorLabel:'Cor',trackLabel:'Acabamento',secondaryProductLabel:'Produto secundário',summaryTitle:'Resumo',addToCartLabel:'Adicionar ao carrinho'},medidas:{larguraMinima:.5,larguraMaxima:12,alturaMinima:.5,alturaEntradaMaxima:5,calculoMaximo:3.2,inicioAcrescimo:999,acrescimoPercentual:0,acimaMaximo:{modo:'consulta',texto:'Medida fora do limite automático. Solicite orçamento personalizado.',textoBotao:'Solicitar orçamento',permitirCarrinho:false}},barra:{faixas:[],acimaInicio:20},franzimentos:blind?[]:[{valor:2,rotulo:'2x'},{valor:2.5,rotulo:'2,5x'},{valor:3,rotulo:'3x'}],tecidos:{},trilhos:{},persiana:{areaMinima:.6,acionamentos:[],ladosComando:['Direito','Esquerdo'],voltagens:['110V','220V','Bivolt']},midia:[],estoqueCombinacoes:{}}}

export async function onRequestGet(context){const auth=await requireFeature(context,'configurator');if(!auth.ok)return auth.response;try{const r=await context.env.DB.prepare(`SELECT config_key,value_json,updated_at FROM store_configs WHERE store_id=?1 AND config_key LIKE 'configurator_%' ORDER BY updated_at ASC`).bind(auth.storeId).all();const map=new Map(BUILT_INS.map(x=>[x.id,{...x,builtin:true}]));for(const row of r.results||[]){try{const c=JSON.parse(row.value_json);const id=String(c.id||row.config_key.replace('configurator_','').replaceAll('_','-'));map.set(id,{id,nome:c.nome||id,icon:c.icon||'◇',tipo:c.tipo||'cortina',ativo:c.ativo!==false,builtin:BUILT_INS.some(x=>x.id===id),updatedAt:row.updated_at||null});}catch{}}return json({ok:true,configurators:[...map.values()]});}catch(e){console.error(e);return json({ok:false,message:'Não foi possível listar os configuradores.'},500)}}

export async function onRequestPost(context){const auth=await requireFeature(context,'configurator');if(!auth.ok)return auth.response;let body={};try{body=await context.request.json()}catch{return json({ok:false,message:'JSON inválido.'},400)}const nome=String(body.nome||'Novo configurador').trim();const tipo=String(body.tipo||'cortina').toLowerCase()==='persiana'?'persiana':'cortina';let id=slugify(body.id||nome)||'configurador';if(BUILT_INS.some(x=>x.id===id))id+='-personalizado';let n=1,base=id;while(await context.env.DB.prepare(`SELECT 1 FROM store_configs WHERE store_id=?1 AND config_key=?2 LIMIT 1`).bind(auth.storeId,'configurator_'+id.replaceAll('-','_')).first()){id=`${base}-${++n}`.slice(0,48)}const cfg=generic(id,nome,tipo),now=new Date().toISOString();await context.env.DB.prepare(`INSERT INTO store_configs(store_id,config_key,value_json,updated_at) VALUES(?1,?2,?3,?4)`).bind(auth.storeId,'configurator_'+id.replaceAll('-','_'),JSON.stringify(cfg),now).run();await logAdmin(context.env.DB,'configurator_created','configurator',id,{nome,tipo},auth.storeId);return json({ok:true,configurator:cfg},201)}
