import {json} from './_lib.js';
import {resolvePublicStore} from './_tenant.js';
import {hasMembership} from './auth/_tenant-account.js';
const enc=new TextEncoder();
function b64u(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64uText(s){return b64u(enc.encode(s))}
function fromB64u(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function cookie(req,name){for(const part of (req.headers.get('cookie')||'').split(';')){const [k,...v]=part.trim().split('=');if(k===name)return decodeURIComponent(v.join('='))}return''}
async function key(secret){return crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify'])}
export async function signSession(context,user){const secret=String(context.env.CUSTOMER_SESSION_SECRET||'');if(secret.length<32)throw new Error('CUSTOMER_SESSION_SECRET inválido.');let version=Number(user.sessionVersion||0);if(!version&&context.env.DB){const r=await context.env.DB.prepare('SELECT session_version FROM customer_accounts WHERE id=?1').bind(user.userId||user.sub).first();version=Number(r?.session_version||1)}const payload={sub:user.sub,userId:user.userId||user.sub,email:user.email,name:user.name||'',picture:user.picture||'',provider:user.provider||'google',emailVerified:user.emailVerified!==false,storeId:String(user.storeId||''),ver:version||1,iat:Date.now(),exp:Date.now()+12*60*60*1000,nonce:crypto.randomUUID()};const body=b64uText(JSON.stringify(payload)),sig=new Uint8Array(await crypto.subtle.sign('HMAC',await key(secret),enc.encode(body)));return body+'.'+b64u(sig)}
export async function readSession(context){const token=cookie(context.request,'__Host-stx_customer');if(!token)return null;const secret=String(context.env.CUSTOMER_SESSION_SECRET||'');if(!secret)return null;const [body,sig]=token.split('.');if(!body||!sig)return null;const ok=await crypto.subtle.verify('HMAC',await key(secret),fromB64u(sig),enc.encode(body));if(!ok)return null;try{const p=JSON.parse(new TextDecoder().decode(fromB64u(body)));return Date.now()>Number(p.exp||0)?null:p}catch{return null}}
export function sessionCookie(token){return `__Host-stx_customer=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${12*60*60}`}
export function clearCookie(){return '__Host-stx_customer=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'}
export async function requireCustomer(context){const user=await readSession(context);if(!user||!context.env.DB)return{ok:false,response:json({ok:false,message:'Faça login para acessar sua conta.'},401)};const store=await resolvePublicStore(context);if(!store||!user.storeId||String(user.storeId)!==String(store.id))return{ok:false,response:json({ok:false,message:'Sua sessão não pertence a esta loja. Entre novamente.'},401,{'Set-Cookie':clearCookie()})};const account=await context.env.DB.prepare(`SELECT id,email,name,phone,picture,provider,email_verified,active,session_version,cpf,cpf_locked,address_json,pending_email,password_hash,password_salt FROM customer_accounts WHERE id=?1`).bind(user.userId).first();if(!account||!account.active||Number(account.session_version||1)!==Number(user.ver||0))return{ok:false,response:json({ok:false,message:'Sua sessão expirou. Entre novamente.'},401,{'Set-Cookie':clearCookie()})};try{const membership=await hasMembership(context.env.DB,store.id,account.id);if(!membership)return{ok:false,response:json({ok:false,message:'Conta não vinculada a esta loja.'},403,{'Set-Cookie':clearCookie()})}}catch(error){console.error('customer_membership_validation_failed',error?.message||String(error));return{ok:false,response:json({ok:false,message:'Não foi possível validar a loja da conta.'},503)}}return{ok:true,user:{...user,email:account.email,name:account.name,emailVerified:Boolean(account.email_verified),sessionVersion:Number(account.session_version||1),storeId:store.id},account,store}}
export function decodeJwtPart(s){try{return JSON.parse(new TextDecoder().decode(fromB64u(s)))}catch{return null}}
export function base64urlBytes(s){return fromB64u(s)}
