(()=>{
let csrf="",companies=[],overview={domains:[],features:[],audit:[]},section="companies";
const $=s=>document.querySelector(s),login=$("#login"),app=$("#app"),content=$("#section-content"),title=$("#section-title"),form=$("#login-form"),token=$("#token"),error=$("#error"),submit=$("#radz-login-button");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;","&#34;":"&quot;",'"':"&quot;","'":"&#39;"}[c]||c));
const labelStatus=s=>({pending_email:"E-mail pendente",trial:"Em teste",active:"Ativa",suspended:"Suspensa",cancelled:"Cancelada",pending:"Pendente",verifying:"Verificando",failed:"Falhou",disabled:"Desativado"}[s]||s||"—");
async function api(url,opt={}){const method=String(opt.method||"GET").toUpperCase(),headers={accept:"application/json","content-type":"application/json",...(opt.headers||{})};if(!["GET","HEAD","OPTIONS"].includes(method)&&csrf)headers["x-csrf-token"]=csrf;const r=await fetch(url,{credentials:"same-origin",...opt,headers});const type=r.headers.get("content-type")||"",d=type.includes("application/json")?await r.json().catch(()=>({})):{};if(!r.ok)throw Object.assign(new Error(d.message||d.code||("Falha ("+r.status+").")),{status:r.status});return d}
async function loadAll(){const [c,o]=await Promise.all([api("/radz/api/companies"),api("/radz/api/overview")]);companies=Array.isArray(c.companies)?c.companies:[];overview=o;render()}
function companyName(id){return companies.find(c=>c.id===id)?.trade_name||"Empresa"}
function metrics(){const active=companies.filter(c=>["active","trial"].includes(c.status)).length,fees=companies.reduce((s,c)=>s+Number(c.platform_fee_basis_points||0),0);return `<div class="metrics"><article><small>EMPRESAS</small><strong>${companies.length}</strong></article><article><small>ATIVAS / TESTE</small><strong>${active}</strong></article><article><small>TAXA MÉDIA</small><strong>${companies.length?(fees/companies.length/100).toFixed(2).replace(".",","):"0,00"}%</strong></article></div>`}
function companiesView(){return metrics()+`<div class="table-wrap"><table><thead><tr><th>Empresa</th><th>CNPJ</th><th>Plano</th><th>Taxa</th><th>Situação</th><th>Domínios</th><th>Usuários</th></tr></thead><tbody>${companies.map(c=>`<tr><td><strong>${esc(c.trade_name)}</strong><small>${esc(c.email)}</small></td><td>${esc(c.document_number)}</td><td>${esc(c.plan_code)}</td><td>${(Number(c.platform_fee_basis_points)/100).toFixed(2).replace(".",",")}%</td><td><span class="status ${esc(c.status)}">${esc(labelStatus(c.status))}</span></td><td>${c.active_domains||0}</td><td>${c.active_users||0}</td></tr>`).join("")}</tbody></table></div>`}
function plansView(){return `<div class="cards">${companies.map(c=>`<form class="config-card plan-form" data-id="${esc(c.id)}"><h2>${esc(c.trade_name)}</h2><label>Plano<input name="plan" value="${esc(c.plan_code)}" maxlength="60"></label><label>Taxa da plataforma (%)<input name="fee" type="number" min="0" max="100" step="0.01" value="${(Number(c.platform_fee_basis_points)/100).toFixed(2)}"></label><label>Situação<select name="status">${["pending_email","trial","active","suspended","cancelled"].map(s=>`<option value="${s}" ${c.status===s?"selected":""}>${labelStatus(s)}</option>`).join("")}</select></label><button type="submit">Salvar configuração</button><p class="form-result" aria-live="polite"></p></form>`).join("")}</div>`}
function layoutsView(){return `<div class="cards">${companies.map(c=>`<article class="config-card"><h2>${esc(c.trade_name)}</h2><p>Layout e conteúdo são editados no painel exclusivo da empresa.</p><a class="primary-link" href="https://salvatex-cortinas.pages.dev/admin/#layout" target="_blank" rel="noopener">Abrir editor da loja ↗</a></article>`).join("")}</div>`}
function featuresView(){const rows=overview.features||[];return `<div class="table-wrap"><table><thead><tr><th>Empresa</th><th>Recurso</th><th>Disponibilidade</th><th>Atualização</th></tr></thead><tbody>${rows.map(f=>`<tr><td>${esc(f.trade_name||companyName(f.company_id))}</td><td>${esc(f.feature_key)}</td><td><span class="status ${f.enabled?"active":"disabled"}">${f.enabled?"Liberado":"Bloqueado"}</span></td><td>${esc(f.updated_at)}</td></tr>`).join("")||'<tr><td colspan="4">Nenhum recurso cadastrado.</td></tr>'}</tbody></table></div>`}
function serviceView(kind){const payment=kind==="payments";return `<div class="cards">${companies.map(c=>`<article class="config-card"><h2>${esc(c.trade_name)}</h2><p><strong>${payment?"Pagamentos":"Fretes"}:</strong> configuração isolada por empresa.</p><p>As credenciais devem permanecer nas variáveis protegidas da empresa e nunca ficam visíveis para a RADZ HUB.</p><span class="status trial">Preparado para integração</span></article>`).join("")}</div>`}
function domainsView(){const rows=overview.domains||[];return `<div class="table-wrap"><table><thead><tr><th>Empresa</th><th>Domínio</th><th>Tipo</th><th>Situação</th><th>Verificação</th></tr></thead><tbody>${rows.map(d=>`<tr><td>${esc(d.trade_name||companyName(d.company_id))}</td><td><strong>${esc(d.hostname)}</strong></td><td>${esc(d.domain_type)}</td><td><span class="status ${esc(d.status)}">${esc(labelStatus(d.status))}</span></td><td>${esc(d.verification_method||"—")}</td></tr>`).join("")||'<tr><td colspan="5">Nenhum domínio cadastrado.</td></tr>'}</tbody></table></div>`}
function auditView(){const rows=overview.audit||[];return `<div class="table-wrap"><table><thead><tr><th>Data</th><th>Empresa</th><th>Ação</th><th>Alvo</th></tr></thead><tbody>${rows.map(a=>`<tr><td>${esc(a.created_at)}</td><td>${esc(a.trade_name||companyName(a.company_id))}</td><td>${esc(a.action)}</td><td>${esc(a.target_type||"—")} ${esc(a.target_id||"")}</td></tr>`).join("")||'<tr><td colspan="4">Nenhum evento registrado.</td></tr>'}</tbody></table></div>`}
function metaView(){const q=new URLSearchParams(location.search),status=q.get("meta")||"",detail=q.get("detail")||"";const messages={oauth_verified:["Autorização validada","A Meta confirmou a conta e o fluxo OAuth está funcionando."],cancelled:["Conexão cancelada","A autorização foi cancelada antes de concluir."],config_error:["Configuração incompleta","Revise as variáveis META_APP_ID, META_APP_SECRET e META_OAUTH_REDIRECT_URI."],state_error:["Sessão de autorização inválida","Inicie uma nova conexão pelo botão abaixo."],code_missing:["Código não recebido","Inicie uma nova conexão pelo botão abaixo."],token_error:["Falha na autorização","A Meta não validou o código de autorização."],profile_error:["Conta não validada","A autorização chegou, mas a conta Meta não pôde ser validada."],error:["Falha inesperada","Tente iniciar a conexão novamente."]};const msg=messages[status];return `<div class="cards"><article class="config-card"><h2>Integração Meta Ads</h2><p>Conecte a plataforma RADZ HUB à Meta usando o fluxo OAuth oficial. O App Secret permanece somente no backend.</p>${msg?`<p class="form-result"><strong>${esc(msg[0])}</strong><br>${esc(detail||msg[1])}</p>`:""}<a class="primary-link" href="/api/oauth/meta/start">Conectar / testar Meta ↗</a><p><small>Permissões atuais: ads_read, ads_management e business_management.</small></p></article><article class="config-card"><h2>Status da implementação</h2><p><span class="status active">OAuth configurado</span></p><p>O callback valida a autorização e a conta Meta. Tokens de acesso ainda não são persistidos até a camada de credenciais criptografadas multiempresa estar concluída.</p><p>Próxima etapa: cofre de credenciais por empresa e seleção da conta de anúncios autorizada.</p></article></div>`}
const names={companies:"Empresas",plans:"Planos e taxas",layouts:"Layouts",features:"Recursos",payments:"Pagamentos",shipping:"Fretes",domains:"Domínios",meta:"Meta Ads",audit:"Auditoria"};
function render(){title.textContent=names[section];content.innerHTML=section==="companies"?companiesView():section==="plans"?plansView():section==="layouts"?layoutsView():section==="features"?featuresView():section==="payments"?serviceView("payments"):section==="shipping"?serviceView("shipping"):section==="domains"?domainsView():section==="meta"?metaView():auditView();if(section==="plans")document.querySelectorAll(".plan-form").forEach(f=>f.addEventListener("submit",savePlan))}
async function savePlan(e){e.preventDefault();const f=e.currentTarget,out=f.querySelector(".form-result"),button=f.querySelector("button");button.disabled=true;out.textContent="Salvando…";try{await api("/radz/api/companies",{method:"PATCH",body:JSON.stringify({id:f.dataset.id,planCode:f.plan.value.trim(),platformFeeBasisPoints:Math.round(Number(f.fee.value)*100),status:f.status.value})});out.textContent="Configuração salva.";await loadAll()}catch(x){out.textContent=x.message}finally{button.disabled=false}}
async function boot(){try{const s=await api("/radz/api/session");csrf=s.csrfToken||"";login.hidden=true;app.hidden=false;const q=new URLSearchParams(location.search);if(q.has("meta")){section="meta";document.querySelectorAll("#radz-nav button").forEach(x=>x.classList.toggle("active",x.dataset.section==="meta"))}await loadAll();return true}catch{csrf="";login.hidden=false;app.hidden=true;return false}}
form.addEventListener("submit",async e=>{e.preventDefault();const value=token.value.trim();error.textContent="";if(!value){error.textContent="Digite a chave de acesso.";return}submit.disabled=true;submit.textContent="Verificando…";try{const r=await api("/radz/api/login",{method:"POST",body:JSON.stringify({token:value})});csrf=r.csrfToken||"";if(!await boot())throw new Error("Sessão criada, mas o painel não pôde ser carregado.")}catch(x){error.textContent=x.status===401?"Chave incorreta. Limpe e digite novamente.":x.message;token.select()}finally{submit.disabled=false;submit.textContent="Entrar"}});
$("#toggle-token").addEventListener("click",e=>{const show=token.type==="password";token.type=show?"text":"password";e.currentTarget.textContent=show?"Ocultar":"Mostrar"});
$("#clear-token").addEventListener("click",()=>{token.value="";token.type="password";$("#toggle-token").textContent="Mostrar";error.textContent="Chave limpa.";token.focus()});
$("#radz-nav").addEventListener("click",e=>{const b=e.target.closest("[data-section]");if(!b)return;section=b.dataset.section;document.querySelectorAll("#radz-nav button").forEach(x=>x.classList.toggle("active",x===b));render()});
$("#refresh").addEventListener("click",async()=>{try{await loadAll()}catch(x){content.innerHTML=`<div class="config-card"><h2>Não foi possível atualizar</h2><p>${esc(x.message)}</p></div>`}});
$("#logout").addEventListener("click",async()=>{await api("/radz/api/logout",{method:"POST"}).catch(()=>{});csrf="";location.reload()});
boot();
})();