(()=>{
  let csrf="";
  const login=document.querySelector("#login"),app=document.querySelector("#app"),body=document.querySelector("#companies"),metrics=document.querySelector("#metrics");
  const form=document.querySelector("#login-form"),token=document.querySelector("#token"),error=document.querySelector("#error"),submit=document.querySelector("#radz-login-button");
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  async function api(url,opt={}){const method=String(opt.method||"GET").toUpperCase();const headers={accept:"application/json","content-type":"application/json",...(opt.headers||{})};if(!["GET","HEAD","OPTIONS"].includes(method)&&csrf)headers["x-csrf-token"]=csrf;const r=await fetch(url,{credentials:"same-origin",...opt,headers});const type=r.headers.get("content-type")||"";const d=type.includes("application/json")?await r.json().catch(()=>({})):{};if(!r.ok)throw Object.assign(new Error(d.message||d.code||("Falha no acesso ("+r.status+").")),{status:r.status});return d}
  async function load(){const d=await api("/radz/api/companies");const companies=Array.isArray(d.companies)?d.companies:[];const active=companies.filter(c=>c.status==="active"||c.status==="trial").length;const fees=companies.reduce((s,c)=>s+Number(c.platform_fee_basis_points||0),0);metrics.innerHTML=`<article><small>EMPRESAS</small><strong>${companies.length}</strong></article><article><small>ATIVAS / TESTE</small><strong>${active}</strong></article><article><small>TAXA MÉDIA</small><strong>${companies.length?(fees/companies.length/100).toFixed(2).replace(".",","):"0,00"}%</strong></article>`;body.innerHTML=companies.map(c=>`<tr><td><strong>${esc(c.trade_name)}</strong><small>${esc(c.email)}</small></td><td>${esc(c.document_number)}</td><td>${esc(c.plan_code)}</td><td>${(Number(c.platform_fee_basis_points)/100).toFixed(2).replace(".",",")}%</td><td><span class="status ${esc(c.status)}">${esc(c.status)}</span></td><td>${c.active_domains||0}</td><td>${c.active_users||0}</td></tr>`).join("")}
  async function boot(){try{const session=await api("/radz/api/session");csrf=session.csrfToken||"";login.hidden=true;app.hidden=false;await load();return true}catch{csrf="";login.hidden=false;app.hidden=true;return false}}
  form.addEventListener("submit",async e=>{e.preventDefault();const value=token.value.trim();error.textContent="";if(!value){error.textContent="Digite a chave de acesso.";token.focus();return}submit.disabled=true;submit.textContent="Verificando…";try{const result=await api("/radz/api/login",{method:"POST",body:JSON.stringify({token:value})});csrf=result.csrfToken||"";const opened=await boot();if(!opened)throw new Error("Sessão criada, mas o painel não pôde ser carregado.")}catch(x){error.textContent=x.status===401?"Chave incorreta. Clique em “Limpar chave salva” e digite a senha RADZ novamente.":(x.message||"Não foi possível entrar.");token.select()}finally{submit.disabled=false;submit.textContent="Entrar"}});
  document.querySelector("#toggle-token").addEventListener("click",e=>{const show=token.type==="password";token.type=show?"text":"password";e.currentTarget.textContent=show?"Ocultar":"Mostrar";e.currentTarget.setAttribute("aria-label",show?"Ocultar senha":"Mostrar senha")});
  document.querySelector("#clear-token").addEventListener("click",()=>{token.value="";token.type="password";document.querySelector("#toggle-token").textContent="Mostrar";error.textContent="Chave limpa. Digite a senha RADZ HUB.";token.focus()});
  document.querySelector("#refresh").addEventListener("click",load);
  document.querySelector("#logout").addEventListener("click",async()=>{await api("/radz/api/logout",{method:"POST"}).catch(()=>{});csrf="";location.reload()});
  boot();
})();
